# Generated by Django 5.1.6 on 2025-02-15 18:29

"""Módulo de migrações do Django.

Este módulo é gerado automaticamente pelo Django para gerenciar alterações no esquema do banco de dados.

Componentes principais:
    - migrations: Módulo que fornece suporte para migrações de banco de dados.
    - models: Módulo que fornece suporte para definição de modelos de dados.

Descrição:
    Este módulo contém as operações necessárias para a migração do banco de dados, permitindo a
    criação, alteração ou exclusão de tabelas e campos, conforme definido nas migrações do projeto.
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Migração inicial para o modelo Category.

    Esta classe define a migração inicial para o modelo 'Category', incluindo a criação da tabela
    no banco de dados e suas respectivas colunas.

    Atributos:
        - initial: Indica que esta é a migração inicial.
        - dependencies: Lista de migrações das quais esta migração depende (vazia para migrações iniciais).
        - operations: Lista de operações a serem executadas durante a migração.
    """

    initial = True

    dependencies = [
        # Sem dependências para esta migração inicial
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100),
                ),
                (
                    "description",
                    models.TextField(),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
