# Generated by Django 5.1.6 on 2025-02-15 18:29

"""Módulo de migrações do Django.

Este módulo é gerado automaticamente pelo Django para gerenciar alterações no esquema do banco de dados.

Componentes principais:
    - migrations: Módulo que fornece suporte para migrações de banco de dados.
    - models: Módulo que fornece suporte para definição de modelos de dados.

Descrição:
    Este módulo contém as operações necessárias para a migração do banco de dados, permitindo a
    criação, alteração ou exclusão de tabelas e campos, conforme definido nas migrações do projeto.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Migração inicial para o modelo Inflow.

    Esta classe define a migração inicial para o modelo 'Inflow', incluindo a criação da tabela
    no banco de dados e suas respectivas colunas.

    Atributos:
        - initial: Indica que esta é a migração inicial.
        - dependencies: Lista de migrações das quais esta migração depende (inclui migrações iniciais dos modelos Product e Supplier).
        - operations: Lista de operações a serem executadas durante a migração.
    """

    initial = True

    dependencies = [
        (
            "products",
            "0001_initial",
        ),
        (
            "suppliers",
            "0001_initial",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Inflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inflows",
                        to="products.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inflows",
                        to="suppliers.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
